
import data from "./data"
import { useEffect, useState } from "react";

const Board = ({ selectedStation }) => {
    const [UnitsData, setUnitsData] = useState(data.station1[3].daily);
    useEffect(() => {
        setUnitsData(data[selectedStation][3].daily);
    }, [selectedStation]);

    return (
        <div className="bg-gray-950  py-8 w-[100%] flex flex-col  justify-start">
            <h1 className="md:text-5xl text-3xl font-bold text-gray-200 font-sans">
                Welcome Back to Solar Spot!

                <p className="font-semibold text-sm md:text-lg py-4 text-gray-400">
                    Here at solar spot you can find the units of power generated by the solar panels.
                </p>
            </h1>
            <div className="flex flex-row justify-between md:text-xl text-lg  text-gray-500">
                <h1>
                    Power Generated: <span className="text-white">{UnitsData} Units</span>
                </h1>
                <h1>
                    Location: <span className="text-blue-300"> {selectedStation}</span>
                </h1>
            </div>
        </div>
    )
}

export default Board