import { LineChart, Line, CartesianGrid, XAxis, YAxis, Tooltip, ResponsiveContainer } from 'recharts';
import data from './data.js';
import { useState, useEffect } from 'react';


const Graph = ({ selectedStation }) => {
    const [chartData, setChartData] = useState(data.station1);
    useEffect(() => {
        setChartData(data[selectedStation]);
    }, [selectedStation]);

    return (
        <div className='w-[100%] md:h-[70%] h-[50%] text-white flex flex-col justify-start p-4 md:gap-8 items-d md:p-8 bg-gray-800/50 rounded-md'>
            <h1 className='md:text-2xl text-gray-300 text-lg'>
                Power Generated by Solar Panels:
            </h1>
            <ResponsiveContainer width="100%" height="100%">
                <LineChart width={700} height={300} data={chartData} margin={{ top: 5, right: 20, bottom: 5, left: 0 }}>
                    <Line type="monotone" dataKey="gen" stroke="#8884d8" />
                    <Line type="monotone" dataKey="used" stroke="#E2C2C6" />
                    <CartesianGrid stroke="#969696" strokeDasharray="5 5" />
                    <XAxis dataKey="name" stroke='#ffffff' />
                    <YAxis stroke='#ffffff' />
                    <Tooltip />
                </LineChart>
            </ResponsiveContainer>
        </div>
    )
}

export default Graph